# Generated by Django 4.1.7 on 2023-04-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='show_author',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, help_text='If the author should be shown in the list of posts. This is just a flag - the template has to be coded appropriately for this to work', verbose_name='show author'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='show_created',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, help_text='If the creation date should be shown in the list of posts. This is just a flag - the template has to be coded appropriately for this to work'),
        ),
        migrations.AlterField(
            model_name='post',
            name='show_author',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Use Placement Choice')], default=2, help_text='If the author should be shown in the detail view. This is just a flag - the template has to be coded appropriately for this to work', verbose_name='show author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='show_created',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Use Placement Choice')], default=2, help_text='If the creation date should be shown in the detail view. This is just a flag - the template has to be coded appropriately for this to work', verbose_name='show created'),
        ),
    ]
