# Generated by Django 4.1.7 on 2023-04-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0003_article_articleplacement_articleimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleeventdate',
            options={'ordering': ('-whendate', '-whentime', 'article')},
        ),
        migrations.RenameField(
            model_name='articleeventdate',
            old_name='whenday',
            new_name='whendate',
        ),
        migrations.AddField(
            model_name='articleeventdate',
            name='timelen',
            field=models.IntegerField(default=0, help_text='The length of time for the event in minutes', verbose_name='length(minutes)'),
        ),
        migrations.AddField(
            model_name='articleeventdate',
            name='whentime',
            field=models.TimeField(blank=True, help_text='The start time of the event', null=True, verbose_name='time'),
        ),
    ]
