# Generated by Django 4.1.7 on 2023-04-22 18:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    Article = apps.get_model("tougcomsys", "Article")
    Post = apps.get_model("tougcomsys", "Post")
    Page = apps.get_model("tougcomsys", "Page")
    Event = apps.get_model("tougcomsys", "Event")
    Image = apps.get_model("tougcomsys", "Image")
    Placement = apps.get_model("tougcomsys", "Placement")
    EventDate = apps.get_model("tougcomsys", "EventDate")
    PostImage = apps.get_model("tougcomsys", "PostImage")
    ArticleImage = apps.get_model("tougcomsys", "ArticleImage")
    ArticlePlacement = apps.get_model("tougcomsys", "ArticlePlacement")
    ArticleEventdate = apps.get_model("tougcomsys", "ArticleEventdate")

    db_alias = schema_editor.connection.alias
    posts = Post.objects.using(db_alias).all()
    for post in posts:
        article = Article.objects.using(db_alias).create(
            headline=post.title,
            content_format=post.content_format,
            content=post.content,
            summary_format=post.summary_format,
            summary=post.summary,
            show_author=post.show_author,
            show_updated=post.show_created,
            created_date=post.created,
            updated_date=post.created,
            sortable_date=post.sortable_date,
            sticky=post.sticky,
            draft_status=post.draft_status,
            slug=post.slug,
        )
        article.save()
        if post.list_image:
            articleimage = ArticleImage.objects.using(db_alias).create(
                article=article,
                image=post.list_image,
                shown_on_list=True,
            )
            articleimage.save()
        if post.above_content_image:
            if not articleimage:
               articleimage = ArticleImage.objects.using(db_alias).create(
                    article=article,
                    image=post.above_content_image,
               )
               articleimage.above_content_image_attributes=post.above_content_image_attributes
               articleimage.above_content_image_link=post.above_content_image_link
               articleimage.above_link_attributes=post.above_link_attributes
            articleimage.save()
        if post.below_content_image:
            if not articleimage:
               articleimage = ArticleImage.objects.using(db_alias).create(
                    article=article,
                    image=post.below_content_image,
               )
               articleimage.below_content_image_attributes=post.below_content_image_attributes
               articleimage.below_content_image_link=post.below_content_image_link
               articleimage.below_link_attributes=post.below_link_attributes
            articleimage.save()

        if post.placement:
            articleplacement = ArticlePlacement.objects.using(db_alias).create(
                article=article,
                placement=post.placement
            )
            articleplacement.save()


    pages = Page.objects.using(db_alias).all()
    for page in pages:
        article = Article.objects.using(db_alias).create(
            headline=page.title,
            content_format=page.content_format,
            content=page.content,
            created_date=page.created,
            updated_date=page.created,
            draft_status=page.draft_status,
            slug=page.slug,
        )
        article.save()

        if page.above_content_image:
            if not articleimage:
               articleimage = ArticleImage.objects.using(db_alias).create(
                    article=article,
                    image=page.above_content_image,
               )
               articleimage.above_content_image_attributes=page.above_content_image_attributes
               articleimage.above_content_image_link=page.above_content_image_link
               articleimage.above_link_attributes=page.above_link_attributes
            articleimage.save()
        if page.below_content_image:
            if not articleimage:
               articleimage = ArticleImage.objects.using(db_alias).create(
                    article=article,
                    image=page.below_content_image,
               )
               articleimage.below_content_image_attributes=page.below_content_image_attributes
               articleimage.below_content_image_link=page.below_content_image_link
               articleimage.below_link_attributes=page.below_link_attributes
            articleimage.save()

    events = Event.objects.using(db_alias).all()
    for event in events:
        article = Article.objects.using(db_alias).create(
            headline=event.title,
            content_format=event.content_format,
            content=event.content,
            summary_format=event.summary_format,
            summary=event.summary,
            draft_status=event.draft_status,
            slug=event.slug,
        )
        article.save()
        if event.list_image:
            articleimage = ArticleImage.objects.using(db_alias).create(
                article=article,
                image=event.list_image,
                shown_on_list=True,
            )
            articleimage.save()
        if event.above_content_image:
            if not articleimage:
               articleimage = ArticleImage.objects.using(db_alias).create(
                    article=article,
                    image=event.above_content_image,
               )
               articleimage.above_content_image_attributes=event.above_content_image_attributes
               articleimage.above_content_image_link=event.above_content_image_link
               articleimage.above_link_attributes=event.above_link_attributes
            articleimage.save()
        if event.below_content_image:
            if not articleimage:
               articleimage = ArticleImage.objects.using(db_alias).create(
                    article=article,
                    image=event.below_content_image,
               )
               articleimage.below_content_image_attributes=event.below_content_image_attributes
               articleimage.below_content_image_link=event.below_content_image_link
               articleimage.below_link_attributes=event.below_link_attributes
            articleimage.save()
        for eventdate in event.eventdate_set.all():
            articleeventdate = ArticleEventdate.objects.using(db_alias).create(
                article=article,
                whendate=eventdate.whenday,
                whentime=event.starttime,
                timelen=event.lenmin,
            )
               

    


class Migration(migrations.Migration):
    atomic = False  
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tougcomsys', '0004_alter_articleeventdate_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            forwards_func
        )
    ]
