# Generated by Django 4.1.7 on 2023-04-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0005_populate_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdate',
            name='event',
        ),
        migrations.RemoveField(
            model_name='page',
            name='above_content_image',
        ),
        migrations.RemoveField(
            model_name='page',
            name='author',
        ),
        migrations.RemoveField(
            model_name='page',
            name='below_content_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='above_content_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='below_content_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='list_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='placement',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventDate',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
