# Generated by Django 4.1.7 on 2023-04-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0006_remove_eventdate_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='above_content_image_attributes',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='above_content_image_attributes',
            field=models.CharField(blank=True, help_text='The attributes (ie style="width:60%") for the image for if/when the image is displayed in a list', max_length=200, verbose_name='above content image attributes'),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='list_image_link',
            field=models.URLField(blank=True, help_text='The link for the image if/when displayed list content', verbose_name='list image link'),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='list_image_link_attributes',
            field=models.CharField(blank=True, help_text='The attributes (ie target="_blank") for the link for if/when the image is displayed list content', max_length=70, verbose_name='list image link attributes'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='The slug used to refer to this article', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='above_content_image_link',
            field=models.URLField(blank=True, help_text='The link for the image if/when displayed list content', verbose_name='above content image link'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='above_content_link_attributes',
            field=models.CharField(blank=True, help_text='The attributes (ie target="_blank") for the link for if/when the image is displayed list content', max_length=70, verbose_name='above content link attributes'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='below_content_image_attributes',
            field=models.CharField(blank=True, help_text='The attributes (ie style="width:60%") for the image for if/when the image is displayed below content', max_length=200, verbose_name='below content image attributes'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='below_content_image_link',
            field=models.URLField(blank=True, help_text='The link for the image if/when displayed below content', verbose_name='below content image link'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='list_image_attributes',
            field=models.CharField(blank=True, help_text='The attributes (ie style="width:60%") for the image for if/when the image is displayed list content', max_length=200, verbose_name='list image attributes'),
        ),
    ]
