# Generated by Django 4.1.7 on 2023-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0008_alter_articleimage_shown_above_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subheadline',
            field=models.CharField(blank=True, help_text='The optional subtitle or subheadline of the article', max_length=100, verbose_name='Headline'),
        ),
    ]
