# Generated by Django 4.1.7 on 2023-04-24 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0009_alter_article_subheadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the menu', max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='articleeventdate',
            options={'ordering': ('whendate', '-whentime', 'article')},
        ),
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The title of the image', max_length=100, verbose_name='label')),
                ('url', models.URLField(blank=True, help_text='The URL.  This will be overwritten if an article is chosen', verbose_name='URL')),
                ('article', models.ForeignKey(blank=True, help_text='The article that this item links to - can be blank if URL is entered and no article needs to be chosen. Removed and replaced by URL of article when this link is saved.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tougcomsys.article')),
            ],
        ),
        migrations.CreateModel(
            name='Menuitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The label to be displayed', max_length=30, verbose_name='label')),
                ('short_label', models.CharField(help_text='A shorter version of the label to be displayed on compact menus', max_length=10, verbose_name='short label')),
                ('url', models.URLField(help_text='The URL that this menu links to', verbose_name='URL')),
                ('sort_number', models.IntegerField(default=0, help_text='A number used to determine the order of placement on a menu', verbose_name='Sort Number')),
                ('menu', models.ForeignKey(blank=True, help_text='The menu to which this item is attached', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tougcomsys.menu')),
            ],
        ),
    ]
