# Generated by Django 4.1.7 on 2023-04-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0010_menu_alter_articleeventdate_options_menulink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='link',
            field=models.ForeignKey(help_text='The link that this menu item links to', null=True, on_delete=django.db.models.deletion.CASCADE, to='tougcomsys.menulink'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(help_text='The menu to which this item is attached', on_delete=django.db.models.deletion.CASCADE, to='tougcomsys.menu'),
        ),
    ]
