# Generated by Django 4.1.7 on 2023-04-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0011_remove_menuitem_url_menuitem_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='label',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='short_label',
        ),
        migrations.AlterField(
            model_name='menulink',
            name='url',
            field=models.CharField(blank=True, help_text='The URL.  This will be overwritten if an article is chosen', max_length=250, verbose_name='URL'),
        ),
    ]
