# Generated by Django 4.1.7 on 2023-04-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0013_remove_menuitem_sort_number_menu_sort_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='draft_status',
            field=models.IntegerField(choices=[(7, 'Published'), (5, 'No Preview'), (0, 'Draft')], default=0, help_text='The status of this menu.'),
        ),
    ]
