# Generated by Django 4.2 on 2023-05-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0014_menu_draft_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='readmore',
            field=models.CharField(blank=True, default='Read More', help_text='The text to use for the "read more" link ', max_length=30, verbose_name='read more text'),
        ),
    ]
