# Generated by Django 4.1.7 on 2023-06-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0015_article_readmore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="An optional name to be given to this calendar.  The calendar's own name will be used if this is blank", max_length=50, verbose_name='name')),
                ('url', models.URLField(help_text='The URL of the external calendar', verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='IcsSupress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(help_text='The UUID of the external event to be supressed', max_length=264, verbose_name='uuid')),
                ('ics', models.ForeignKey(help_text='The calendar of the event to be supressed', on_delete=django.db.models.deletion.CASCADE, to='tougcomsys.ics')),
            ],
        ),
    ]
