# Generated by Django 4.1.7 on 2023-06-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0016_ics_icssupress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icssupress',
            name='ics',
        ),
        migrations.AddField(
            model_name='icssupress',
            name='name',
            field=models.CharField(blank=True, help_text='An optional name to be given to this event.', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ics',
            name='name',
            field=models.CharField(blank=True, help_text='An optional name to be given to this calendar.', max_length=50, verbose_name='name'),
        ),
    ]
