# Generated by Django 4.1.7 on 2023-06-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0018_rename_icssupress_blockedicalevent_rename_ics_ical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subheadline',
            field=models.CharField(blank=True, help_text='The optional subtitle or subheadline of the article', max_length=100, verbose_name='Sub Headline'),
        ),
    ]
