# Generated by Django 4.1.7 on 2023-06-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0019_alter_article_subheadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleplacement',
            options={'ordering': ('article',)},
        ),
    ]
