# Generated by Django 4.1.7 on 2023-06-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0020_alter_articleplacement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt_text',
            field=models.CharField(blank=True, help_text='The alternet text for the image', max_length=255, verbose_name='alt text'),
        ),
    ]
