# Generated by Django 4.2.2 on 2023-06-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0021_image_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedicalevent',
            name='ical',
            field=models.ForeignKey(blank=True, help_text='The ical of the event to be blocked', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tougcomsys.ical'),
        ),
    ]
