# Generated by Django 4.2.2 on 2023-06-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0023_blockedicalevent_display_instead'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='descriptive_date',
            field=models.CharField(blank=True, help_text='A descriptive date, such as "New Year\\s Day", or "The Third Monday Each Month". Always use this for recurring ical events', max_length=50, verbose_name='descriptive date'),
        ),
    ]
