# Generated by Django 4.1.7 on 2023-06-17 10:44

from django.db import migrations, models
import tougcomsys.models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0024_article_descriptive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='event_date_until',
            field=models.DateField(default=tougcomsys.models.plus_366, help_text='For event placements, the last date to show', verbose_name='show events until'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='show_created',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, help_text='If the creation date should be shown in the list of posts. This is just a flag - the template has to be coded appropriately for this to work', verbose_name='show created date'),
        ),
    ]
