# Generated by Django 4.1.7 on 2023-06-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0027_placement_show_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleplacement',
            name='placement',
            field=models.ForeignKey(blank=True, help_text='The placement on the template (for events - no placement indicates event should be on any calendar)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tougcomsys.placement'),
        ),
    ]
