# Generated by Django 4.1.7 on 2023-06-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0029_remove_placement_event_date_until_ical_placement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='page',
            field=models.IntegerField(default=0, help_text='The page on which this placement should appear', verbose_name='page'),
        ),
    ]
