# Generated by Django 4.1.7 on 2023-06-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0033_remove_menu_sort_name_remove_menuitem_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the page', max_length=30, verbose_name='name')),
                ('is_home', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, help_text='If this is the home page.  Only one will be used as home page even if more than one is chosen')),
            ],
            options={
                'ordering': ('-is_home', 'pk'),
            },
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('pagex', 'menu_number')},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='page',
            new_name='pagex',
        ),
        migrations.RenameField(
            model_name='placement',
            old_name='page',
            new_name='pagex',
        ),
    ]
