# Generated by Django 4.1.7 on 2023-06-18 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0034_page_alter_menu_options_rename_page_menu_pagex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('page', 'menu_number')},
        ),
        migrations.AddField(
            model_name='menu',
            name='page',
            field=models.ForeignKey(blank=True, help_text='The page on which this menu should be displayed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tougcomsys.page'),
        ),
        migrations.AddField(
            model_name='placement',
            name='page',
            field=models.ForeignKey(blank=True, help_text='The page on which this placement should appear', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tougcomsys.page'),
        ),
    ]
