# Generated by Django 4.1.7 on 2023-06-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0036_menulink_page_alter_menulink_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='link',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='article',
            field=models.ForeignKey(blank=True, help_text='The article that this item links to - can be blank if a page or URL is entered and no article needs to be chosen. Removed and replaced by URL of article or page when this link is saved.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tougcomsys.article'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(blank=True, help_text='The page that this item links to - can be blank if article or URL is entered and no page needs to be chosen. Removed and replaced by URL of article or page when this link is saved.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tougcomsys.page'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, help_text='The URL.  This will be overwritten if an article or page is chosen', max_length=250, verbose_name='URL'),
        ),
        migrations.DeleteModel(
            name='MenuLink',
        ),
    ]
