# Generated by Django 4.1.7 on 2023-06-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0039_alter_placement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='column_widths',
            field=models.CharField(blank=True, help_text='A comma separated list of relative column widths (ex: "2,1,1" for the first column being twice as wide as others)', max_length=30, verbose_name='column_widths'),
        ),
    ]
