# Generated by Django 4.1.7 on 2023-06-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0041_remove_articleimage_above_content_image_attributes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='shown_in_detail',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='shown_in_list',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='show_in_detail',
            field=models.CharField(blank=True, choices=[('', 'No'), ('top', 'Above Content'), ('right', 'Right of Content'), ('bottom', 'Below Content'), ('left', 'Left of Content')], default='', help_text='If and where this image should be displayed with in a detail view of this article', max_length=10, verbose_name='show in detail view'),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='show_in_list',
            field=models.CharField(blank=True, choices=[('', 'No'), ('top', 'Above Content'), ('right', 'Right of Content'), ('bottom', 'Below Content'), ('left', 'Left of Content')], default='', help_text="If and where this image should be displayed with this article's headline and summary on a list of articles", max_length=10, verbose_name='show in list view'),
        ),
    ]
