# Generated by Django 4.1.7 on 2023-06-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0042_remove_articleimage_shown_in_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='column_widths',
        ),
        migrations.AddField(
            model_name='placement',
            name='column_width',
            field=models.IntegerField(choices=[(0, 'Narrow'), (1, 'Wide')], default=0, help_text='The width of the column. The template may ingore this setting either completely or for certain media types', verbose_name='column width'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='type',
            field=models.IntegerField(choices=[(0, 'Article List'), (1, 'Event List')], help_text='The type of placement', verbose_name='type'),
        ),
    ]
