# Generated by Django 4.1.7 on 2023-06-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0043_remove_page_column_widths_placement_column_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='show_in_detail',
            field=models.CharField(blank=True, choices=[('', 'No'), ('top', 'Above Content'), ('side', 'Beside Content'), ('bottom', 'Below Content')], default='', help_text='If and where this image should be displayed with in a detail view of this article. Image display may vary by theme', max_length=10, verbose_name='show in detail view'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='show_in_list',
            field=models.CharField(blank=True, choices=[('', 'No'), ('top', 'Above Content'), ('side', 'Beside Content'), ('bottom', 'Below Content')], default='', help_text="If and where this image should be displayed with this article's headline and summary on a list of articles. *Note*: side images may be hidden or moved in narrow columns. Image display may be vary by theme.", max_length=10, verbose_name='show in list view'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='column_width',
            field=models.IntegerField(blank=True, choices=[('narrow', 'Narrow'), ('wide', 'Wide')], help_text='The width of the column. The template may ingore this setting either completely or for certain media types', null=True, verbose_name='column width'),
        ),
    ]
