# Generated by Django 4.1.7 on 2023-06-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0045_alter_placement_column_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='list_image_attributes',
            field=models.CharField(blank=True, help_text='The attributes (ie style="width:60%") for the image for if/when the image is displayed list content.', max_length=200, verbose_name='list image attributes'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='show_in_detail',
            field=models.CharField(blank=True, choices=[('', 'No'), ('top', 'Above Content'), ('side', 'Right of Content'), ('bottom', 'Below Content')], default='', help_text='If and where this image should be displayed with in a detail view of this article. Image display may vary by theme', max_length=10, verbose_name='show in detail view'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='show_in_list',
            field=models.CharField(blank=True, choices=[('', 'No'), ('top', 'Above Content'), ('side', 'Right of Content'), ('bottom', 'Below Content')], default='', help_text="If and where this image should be displayed with this article's headline and summary on a list of articles. *Note*: side images may be hidden or moved in narrow columns. Image display may be vary by theme.", max_length=10, verbose_name='show in list view'),
        ),
    ]
