# Generated by Django 4.1.7 on 2023-07-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0048_remove_menu_pagex_articleimage_detail_image_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='detail_image',
            field=models.ForeignKey(blank=True, help_text='The image to show in detail view ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_image', to='tougcomsys.image', verbose_name='detail image'),
        ),
        migrations.AddField(
            model_name='article',
            name='detail_image_location',
            field=models.CharField(choices=[('top', 'top only'), ('side', 'side or top'), ('bottom', 'bottom only')], default=('top', 'top only'), help_text='The location of the image. This is just a flag which indicates a preference', max_length=20, verbose_name='detail view image location'),
        ),
        migrations.AddField(
            model_name='article',
            name='list_image',
            field=models.ForeignKey(blank=True, help_text='The image to show in list view ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_image', to='tougcomsys.image', verbose_name='list view image'),
        ),
        migrations.AddField(
            model_name='article',
            name='list_image_location',
            field=models.CharField(choices=[('top', 'top only'), ('side', 'side or top'), ('bottom', 'bottom only')], default=('top', 'top only'), help_text='The location of the image. This is just a flag which indicates a preference', max_length=20, verbose_name='list view image location'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
