# Generated by Django 4.1.7 on 2023-07-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0049_article_detail_image_article_detail_image_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='The image to show in links to this article, where supported ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_image', to='tougcomsys.image', verbose_name='featured image'),
        ),
    ]
