# Generated by Django 4.2 on 2023-07-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0050_article_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='column_width',
            field=models.CharField(blank=True, choices=[('narrow', 'Narrow'), ('wide', 'Wide')], default='narrow', help_text='The width of the column. The template may ingore this setting either completely or for certain media types', max_length=20, null=True, verbose_name='column width'),
        ),
    ]
