# Generated by Django 4.2 on 2023-07-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0051_alter_placement_column_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hashtags',
            field=models.CharField(blank=True, help_text='Hashtags, separated by spaces', max_length=100, verbose_name='hashtags'),
        ),
    ]
