# Generated by Django 4.2 on 2023-07-15 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tougcomsys', '0052_article_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='allow_comments',
            field=models.IntegerField(choices=[('1', 'allow'), ('0', 'none'), ('-1', 'closed')], default=0, help_text='If comments are allowed', verbose_name='allow comments'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(help_text='The article which is to be placed on the site', on_delete=django.db.models.deletion.CASCADE, to='tougcomsys.article')),
                ('commenter', models.ForeignKey(help_text='The user who wrote the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('in_reply_to', models.ForeignKey(blank=True, help_text='The comment to which this comment is a reply', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tougcomsys.comment')),
            ],
        ),
    ]
