# Generated by Django 4.2 on 2023-07-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0053_article_allow_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='', help_text='The comment', verbose_name='comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='allow_comments',
            field=models.IntegerField(choices=[(1, 'allow'), (0, 'none'), (-1, 'closed')], default=0, help_text='If comments are allowed', verbose_name='allow comments'),
        ),
    ]
