# Generated by Django 4.2 on 2023-07-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0056_alter_comment_options_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='in_reply_to_text',
            field=models.TextField(blank=True, help_text='The text of the comment to which this comment is a reply', verbose_name='in reply to'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(help_text='The text of the comment', verbose_name='comment'),
        ),
    ]
