# Generated by Django 4.2 on 2023-07-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0057_comment_in_reply_to_text_alter_comment_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='in_reply_to_author_str',
            field=models.CharField(blank=True, help_text='The author of the comment to which this comment is a reply', max_length=50, verbose_name='in reply to author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='in_reply_to_created_date',
            field=models.TextField(blank=True, help_text='The date of the comment to which this comment is a reply', null=True, verbose_name='in reply to created'),
        ),
    ]
