# Generated by Django 4.1.7 on 2023-07-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0058_comment_in_reply_to_author_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleplacement',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='The date that this article should be removed from this placement', null=True, verbose_name='expiration date'),
        ),
    ]
