# Generated by Django 4.2.4 on 2023-08-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0060_alter_placement_type_feedsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='type',
            field=models.IntegerField(choices=[(0, 'Article List'), (1, 'Event List'), (2, 'Feed')], help_text='The type of placement', verbose_name='type'),
        ),
    ]
