# Generated by Django 4.2 on 2023-09-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0061_alter_placement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='The slug used to refer to this article', verbose_name='slug'),
        ),
    ]
