# Generated by Django 4.2.4 on 2023-09-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0062_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='The slug used to refer to this article', max_length=150, verbose_name='slug'),
        ),
    ]
