# Generated by Django 4.2.4 on 2023-09-27 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0063_alter_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RemoveField(
            model_name='article',
            name='sortable_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sticky',
        ),
        migrations.AddField(
            model_name='articleplacement',
            name='sortable_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='The modifiable date used for sorting posts, Later dates normally appear list earlier dates', null=True, verbose_name='sortable date'),
        ),
        migrations.AddField(
            model_name='articleplacement',
            name='sticky',
            field=models.BooleanField(default=False, help_text='If this post is stuck to the top. This is used before sortable date', verbose_name='sticky'),
        ),
    ]
