# Generated by Django 4.2.4 on 2023-12-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0067_ical_ical_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embed_headlines',
            field=models.BooleanField(default=True, help_text='If the headline and subheadline are included with the embed', verbose_name='embed headlines'),
        ),
        migrations.AddField(
            model_name='article',
            name='embeddable',
            field=models.BooleanField(default=False, help_text='If this article can be embedded', verbose_name='embeddable'),
        ),
    ]
