# Generated by Django 4.2.4 on 2023-12-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0068_article_embed_headlines_article_embeddable'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateField(blank=True, help_text='The publish date. If so configured, and unless the draft status is "archived", an automatic process will ensure the draft status is "published" if the system date is greater than or equal to the publish date, or "draft" if the system date is earlier than the publish date', null=True, verbose_name='publish date'),
        ),
    ]
