# Generated by Django 4.2.4 on 2023-12-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0069_article_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='A URL friendly representation - usually a variation of the headline', max_length=150, unique=True, verbose_name='slug'),
        ),
    ]
