# Generated by Django 4.2.4 on 2024-01-01 01:03

import re
from django.db import migrations
from django.template.defaultfilters import slugify


def make_slugs(apps, schema_editor):
    Page = apps.get_model("tougcomsys", "Page")
    # triggers the automatic creation of a slug
    for page in Page.objects.all():
        if not page.slug > "":
            page.slug = slugify(page.name)

        # check that slug is unique
        found_slugs = Page.objects.filter(slug=page.slug)
        if page.pk:
            found_slugs = found_slugs.exclude(pk=page.pk)

        if found_slugs.exists():
            slug_base = re.match(r"((.(?!_\d+$))*(.(?=_\d+$){0,1}))", page.slug)[0]
            if re.match("^\d$", slug_base):
                slug_base = "_" + slug_base
            slug_number = 1
            # if slug is not unique, add "_n" to the end, n being a number from 1 to 1000
            # give up after 1000 tries
            while found_slugs.count() > 0 and slug_number < 1001:
                page.slug = "{}_{}".format(slug_base, slug_number)
                found_slugs = Page.objects.filter(slug=page.slug)
                if page.pk:
                    found_slugs = found_slugs.exclude(pk=page.pk)

                slug_number = slug_number + 1

        page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("tougcomsys", "0071_page_slug"),
    ]

    operations = [
        migrations.RunPython(make_slugs),
    ]
