# Generated by Django 4.2.4 on 2024-01-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougcomsys', '0072_auto_20231231_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text='A URL friendly representation - usually a variation of the name', max_length=150, unique=True, verbose_name='slug'),
        ),
    ]
